# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# IllinoisInJeopardy_Model.py
# Created on: 2016-10-16 12:58:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: IllinoisInJeopardy_Model <Jeopardy_CSV_File> 
# Description: 
# Illinois is in Jeopardy!
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Jeopardy_CSV_File = arcpy.GetParameterAsText(0)
if Jeopardy_CSV_File == '#' or not Jeopardy_CSV_File:
    Jeopardy_CSV_File = "C:\\Users\\jvwhit\\Documents\\ILGISA\\Data\\Answers_Adv\\CSV\\JeopardyContestants_LatLon.csv" # provide a default value if unspecified

# Local variables:
JeopardyContestants_Table = "C:\\Users\\jvwhit\\Documents\\ILGISA\\Data\\Answers_Adv\\Illinois.gdb\\JeopardyContestants_Table"
Jeopardy_Contestants = "Jeopardy Contestants"
Jeopardy_Contestants_Feature_Class_Output = "C:\\Users\\jvwhit\\Documents\\ILGISA\\Data\\Answers_Adv\\Illinois.gdb\\JeopardyContestants"
Jeopardy_Contestants_Buffer_Output = "C:\\Users\\jvwhit\\Documents\\ILGISA\\Data\\Answers_Adv\\Illinois.gdb\\JeopardyContestants_Buffer"

# Process: Copy Rows
arcpy.CopyRows_management(Jeopardy_CSV_File, JeopardyContestants_Table, "")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(JeopardyContestants_Table, "lon", "lat", Jeopardy_Contestants, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "")

# Process: Select
arcpy.Select_analysis(Jeopardy_Contestants, Jeopardy_Contestants_Feature_Class_Output, "\"lat\" IS NOT NULL OR \"lon\" IS NOT NULL")

# Process: Buffer
arcpy.Buffer_analysis(Jeopardy_Contestants_Feature_Class_Output, Jeopardy_Contestants_Buffer_Output, "5 Miles", "FULL", "ROUND", "NONE", "", "GEODESIC")

